<a href="https://colab.research.google.com/github/Abduba011/moringa_data_science_prep_week3_independent_project_2022_04_abduba_galgalo_datareport/blob/main/Moringa_Data_Science_Prep__Independent_Project_Week4_2022_04_Abduba_Galgalo_Python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

 AN ELECTRIC CAR-SHARING SERVICE COMPANY
 Is a community based  company and platform ,providing electric vehicles as an exclusive amenity to apartments ,hotels and workplaces.They are conveniently located on property with dedicated parking spaces and can be reserved through the Electric Car sharing App.
 The following Dataset will guide us through research questions for the company:

 a).The dataset[[link text](http://bit.ly/autolib_dataset)] 

 b).The Data description [[link text](https://drive.google.com/a/moringaschool.com/file/d/13DXF2CFWQLeYxxHFekng8HJnH_jtbfpN/view?usp=sharing)]

 THE RESEARCH QUESTION:

 1.Identify the most popular hour of the day for picking up a shared electric car (Blue-Car) in the city over the month of April 2018.

 2.What is the most popular hour for the Returning Cars?

 3.What station is the most popular and at the most popular picking hour?

 4.What postal code is the most popular for picking up Blue-Car ? and whether the most popular station belong to that postal code? and the most popular picking hour?

 5.Whether the results changes if consindering Utilib and Utilib 1.4 instead of Blue-Car?

In [1]:
#Import the libraries to be used 
import pandas as pd

In [2]:
#loading and reading the data set from csv file 
#
df = pd.read_csv('http://bit.ly/autolib_dataset')
df.head()

,Address,Cars,Bluecar counter,Utilib counter,Utilib 1.4 counter,Charge Slots,Charging Status,City,Displayed comment,ID,...,Scheduled at,Slots,Station type,Status,Subscription status,year,month,day,hour,minute
0,2 Avenue de Suffren,0,0,0,0,0,nonexistent,Paris,NaN,paris-suffren-2,...,NaN,2,station,ok,nonexistent,2018,4,8,11,43
1,145 Rue Raymond Losserand,6,6,0,0,0,operational,Paris,NaN,paris-raymondlosserand-145,...,NaN,0,station,ok,nonexistent,2018,4,6,7,24
2,2 Avenue John Fitzgerald Kennedy,3,3,0,2,0,operational,Le Bourget,NaN,lebourget-johnfitzgeraldkennedy-2,...,NaN,1,station,ok,nonexistent,2018,4,3,20,14
3,51 Rue EugÃ¨ne OudinÃ©,3,3,1,0,1,operational,Paris,NaN,paris-eugeneoudine-51,...,NaN,2,station,ok,nonexistent,2018,4,4,4,37
4,6 avenue de la Porte de Champerret,3,3,0,0,0,nonexistent,Paris,NaN,paris-portedechamperret-6,...,NaN,3,station,ok,nonexistent,2018,4,8,17,23

In [3]:
#previewing the dataset
#
df.head(10)

,Address,Cars,Bluecar counter,Utilib counter,Utilib 1.4 counter,Charge Slots,Charging Status,City,Displayed comment,ID,...,Scheduled at,Slots,Station type,Status,Subscription status,year,month,day,hour,minute
0,2 Avenue de Suffren,0,0,0,0,0,nonexistent,Paris,NaN,paris-suffren-2,...,NaN,2,station,ok,nonexistent,2018,4,8,11,43
1,145 Rue Raymond Losserand,6,6,0,0,0,operational,Paris,NaN,paris-raymondlosserand-145,...,NaN,0,station,ok,nonexistent,2018,4,6,7,24
2,2 Avenue John Fitzgerald Kennedy,3,3,0,2,0,operational,Le Bourget,NaN,lebourget-johnfitzgeraldkennedy-2,...,NaN,1,station,ok,nonexistent,2018,4,3,20,14
3,51 Rue EugÃ¨ne OudinÃ©,3,3,1,0,1,operational,Paris,NaN,paris-eugeneoudine-51,...,NaN,2,station,ok,nonexistent,2018,4,4,4,37
4,6 avenue de la Porte de Champerret,3,3,0,0,0,nonexistent,Paris,NaN,paris-portedechamperret-6,...,NaN,3,station,ok,nonexistent,2018,4,8,17,23
5,8 Boulevard Voltaire,0,0,0,0,0,nonexistent,Paris,NaN,paris-voltaire-8,...,NaN,4,station,ok,nonexistent,2018,4,6,7,2
6,37 rue Leblanc,0,0,0,0,0,nonexistent,Paris,"Station en parking (niv -1), accÃ¨s 37 rue Leb...",paris-citroencevennes-parking,...,NaN,0,station,closed,nonexistent,2018,4,8,18,20
7,17 Rue des Luaps ProlongÃ©e,3,3,1,0,0,nonexistent,Nanterre,NaN,nanterre-luaps-17,...,NaN,0,station,ok,nonexistent,2018,4,4,22,13
8,34 avenue Jean Moulin,1,1,0,0,0,nonexistent,Paris,NaN,paris-jeanmoulin-34,...,NaN,4,station,ok,nonexistent,2018,4,2,22,58
9,41 boulevard de Rochechouart,6,6,0,0,0,nonexistent,Paris,NaN,paris-anvers-parking,...,NaN,0,station,ok,nonexistent,2018,4,4,15,2

In [4]:
#accessing information about the dataset
#
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 25 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Address              5000 non-null   object
 1   Cars                 5000 non-null   int64
 2   Bluecar counter      5000 non-null   int64
 3   Utilib counter       5000 non-null   int64
 4   Utilib 1.4 counter   5000 non-null   int64
 5   Charge Slots         5000 non-null   int64
 6   Charging Status      5000 non-null   object
 7   City                 5000 non-null   object
 8   Displayed comment    111 non-null    object
 9   ID                   5000 non-null   object
 10  Kind                 5000 non-null   object
 11  Geo point            5000 non-null   object
 12  Postal code          5000 non-null   int64
 13  Public name          5000 non-null   object
 14  Rental status        5000 non-null   object
 15  Scheduled at         47 non-null     object
 16  Slots                5000 non-null   int64
 17  Station type         5000 non-null   object
 18  Status               5000 non-null   object
 19  Subscription status  5000 non-null   object
 20  year                 5000 non-null   int64
 21  month                5000 non-null   int64
 22  day                  5000 non-null   int64
 23  hour                 5000 non-null   int64
 24  minute               5000 non-null   int64
dtypes: int64(12), object(13)
memory usage: 976.7+ KB

CLEANING THE DATA SET :
 Let us perform data cleaning procedures below providing a documentation for our actions and reasons .Try to perform as many as many data cleaning procedures that suits the various dimensions of data.

In [5]:
#checking the validity of the data
#data cleaning action: dropping Displayed comment attribute
#Explanation : we wont need it during analysis ,no question to be answered requires that column
#
df.drop(['Displayed_Comment'], axis =1, inplace= True)
df.head()

KeyError: ignored

In [6]:
#procedure 2:Irrelevant data observation 
#data cleaning action : drop Scheduled at attributes
#
#
df.drop(['Scheduled_at'], axis = 1 , inplace =True)
df.head()
df.info()

KeyError: ignored

In [7]:
#procedures 3
#data cleaning action : checking for duplicated and missing figures 
#
df.duplicated().sum()
df.isnull().sum()

Address                   0
Cars                      0
Bluecar counter           0
Utilib counter            0
Utilib 1.4 counter        0
Charge Slots              0
Charging Status           0
City                      0
Displayed comment      4889
ID                        0
Kind                      0
Geo point                 0
Postal code               0
Public name               0
Rental status             0
Scheduled at           4953
Slots                     0
Station type              0
Status                    0
Subscription status       0
year                      0
month                     0
day                       0
hour                      0
minute                    0
dtype: int64

In [8]:
#for duplicates values 
df.duplicated().sum()

0

In [9]:
#To check the accuracy of the datasets 
#
df.describe()

,Cars,Bluecar counter,Utilib counter,Utilib 1.4 counter,Charge Slots,Postal code,Slots,year,month,day,hour,minute
count,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.0,5000.0,5000.000000,5000.000000,5000.000000
mean,2.333600,2.333600,0.059600,0.123000,0.253400,82634.878400,1.932400,2018.0,4.0,4.941600,11.509200,29.270000
std,2.035274,2.035274,0.246698,0.356506,0.546304,8835.865721,1.905402,0.0,0.0,2.597063,6.893549,17.231741
min,0.000000,0.000000,0.000000,0.000000,0.000000,75001.000000,0.000000,2018.0,4.0,1.000000,0.000000,0.000000
25%,0.000000,0.000000,0.000000,0.000000,0.000000,75012.000000,0.000000,2018.0,4.0,3.000000,6.000000,14.000000
50%,2.000000,2.000000,0.000000,0.000000,0.000000,75019.000000,1.000000,2018.0,4.0,5.000000,11.000000,29.000000
75%,4.000000,4.000000,0.000000,0.000000,0.000000,92320.000000,3.000000,2018.0,4.0,7.000000,18.000000,44.000000
max,7.000000,7.000000,2.000000,3.000000,2.000000,95880.000000,7.000000,2018.0,4.0,9.000000,23.000000,59.000000

EXPORTING THE CLEANED DATASET

In [10]:
#let's export our dataframe into a csv file 
#daframe .to_csv('Autolib2').
#the above daframe is the dataframe which we would like to export .
#I used the to_csv function to create a csv file with the name Autolib2
#and export it 
#
df.to_csv('Autolib2')
df

,Address,Cars,Bluecar counter,Utilib counter,Utilib 1.4 counter,Charge Slots,Charging Status,City,Displayed comment,ID,...,Scheduled at,Slots,Station type,Status,Subscription status,year,month,day,hour,minute
0,2 Avenue de Suffren,0,0,0,0,0,nonexistent,Paris,NaN,paris-suffren-2,...,NaN,2,station,ok,nonexistent,2018,4,8,11,43
1,145 Rue Raymond Losserand,6,6,0,0,0,operational,Paris,NaN,paris-raymondlosserand-145,...,NaN,0,station,ok,nonexistent,2018,4,6,7,24
2,2 Avenue John Fitzgerald Kennedy,3,3,0,2,0,operational,Le Bourget,NaN,lebourget-johnfitzgeraldkennedy-2,...,NaN,1,station,ok,nonexistent,2018,4,3,20,14
3,51 Rue EugÃ¨ne OudinÃ©,3,3,1,0,1,operational,Paris,NaN,paris-eugeneoudine-51,...,NaN,2,station,ok,nonexistent,2018,4,4,4,37
4,6 avenue de la Porte de Champerret,3,3,0,0,0,nonexistent,Paris,NaN,paris-portedechamperret-6,...,NaN,3,station,ok,nonexistent,2018,4,8,17,23
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,8 avenue MÃ©nelotte,2,2,0,0,0,nonexistent,Colombes,NaN,colombes-menelotte-8,...,NaN,3,station,ok,nonexistent,2018,4,6,11,26
4996,37 rue de Dantzig,4,4,0,0,1,operational,Paris,NaN,paris-dantzig-37,...,NaN,2,station,ok,nonexistent,2018,4,4,16,56
4997,142 rue du Bac,1,1,0,0,1,operational,Paris,NaN,paris-bac-142,...,NaN,4,station,ok,nonexistent,2018,4,1,7,1
4998,2 avenue du Val de Fontenay,2,2,0,0,0,nonexistent,Fontenay-Sous-Bois,NaN,fontenaysousbois-valdefontenay-2,...,NaN,3,station,ok,nonexistent,2018,4,4,17,27
4999,5 Rue Henry Brisson,4,4,0,0,0,operational,Paris,NaN,paris-henrybrisson-5,...,NaN,0,station,ok,nonexistent,2018,4,8,10,2

In [11]:
#identify the most popular hour of the day for picking up
# a shared electric car (Blue_Car) in the city over the month of april 2018
#
#
df.describe()
df.head(20)

,Address,Cars,Bluecar counter,Utilib counter,Utilib 1.4 counter,Charge Slots,Charging Status,City,Displayed comment,ID,...,Scheduled at,Slots,Station type,Status,Subscription status,year,month,day,hour,minute
0,2 Avenue de Suffren,0,0,0,0,0,nonexistent,Paris,NaN,paris-suffren-2,...,NaN,2,station,ok,nonexistent,2018,4,8,11,43
1,145 Rue Raymond Losserand,6,6,0,0,0,operational,Paris,NaN,paris-raymondlosserand-145,...,NaN,0,station,ok,nonexistent,2018,4,6,7,24
2,2 Avenue John Fitzgerald Kennedy,3,3,0,2,0,operational,Le Bourget,NaN,lebourget-johnfitzgeraldkennedy-2,...,NaN,1,station,ok,nonexistent,2018,4,3,20,14
3,51 Rue EugÃ¨ne OudinÃ©,3,3,1,0,1,operational,Paris,NaN,paris-eugeneoudine-51,...,NaN,2,station,ok,nonexistent,2018,4,4,4,37
4,6 avenue de la Porte de Champerret,3,3,0,0,0,nonexistent,Paris,NaN,paris-portedechamperret-6,...,NaN,3,station,ok,nonexistent,2018,4,8,17,23
5,8 Boulevard Voltaire,0,0,0,0,0,nonexistent,Paris,NaN,paris-voltaire-8,...,NaN,4,station,ok,nonexistent,2018,4,6,7,2
6,37 rue Leblanc,0,0,0,0,0,nonexistent,Paris,"Station en parking (niv -1), accÃ¨s 37 rue Leb...",paris-citroencevennes-parking,...,NaN,0,station,closed,nonexistent,2018,4,8,18,20
7,17 Rue des Luaps ProlongÃ©e,3,3,1,0,0,nonexistent,Nanterre,NaN,nanterre-luaps-17,...,NaN,0,station,ok,nonexistent,2018,4,4,22,13
8,34 avenue Jean Moulin,1,1,0,0,0,nonexistent,Paris,NaN,paris-jeanmoulin-34,...,NaN,4,station,ok,nonexistent,2018,4,2,22,58
9,41 boulevard de Rochechouart,6,6,0,0,0,nonexistent,Paris,NaN,paris-anvers-parking,...,NaN,0,station,ok,nonexistent,2018,4,4,15,2
10,14 rue Censier,0,0,0,0,2,operational,Paris,NaN,paris-censier-14,...,NaN,6,station,ok,nonexistent,2018,4,1,4,39
11,12 Rue Francis de PressensÃ©,1,1,0,0,0,nonexistent,Puteaux,NaN,puteaux-francisdepressense-12,...,NaN,4,station,ok,nonexistent,2018,4,6,9,20
12,6 avenue de la Porte de Champerret,5,5,1,0,0,nonexistent,Paris,NaN,paris-portedechamperret-6,...,NaN,0,station,ok,nonexistent,2018,4,5,12,22
13,34 avenue Jean Moulin,0,0,0,0,0,nonexistent,Paris,NaN,paris-jeanmoulin-34,...,NaN,0,station,ok,nonexistent,2018,4,8,21,54
14,8 Boulevard Richard Lenoir,0,0,0,0,1,operational,Paris,NaN,paris-richardlenoir-8,...,NaN,4,station,ok,nonexistent,2018,4,6,8,0
15,3 rue Jean JaurÃ¨s,0,0,0,0,0,nonexistent,Fontenay-aux-Roses,NaN,fontenayauxroses-jeanjaures-3,...,NaN,4,full_station,ok,operational,2018,4,2,0,21
16,2 avenue du GÃ©nÃ©ral Leclerc,0,0,0,0,0,nonexistent,Le Chesnay,NaN,lechesnay-leclerc-2,...,NaN,1,station,ok,nonexistent,2018,4,3,19,0
17,182 Boulevard Voltaire,6,6,0,0,0,operational,Paris,NaN,paris-voltaire-182,...,NaN,0,station,ok,nonexistent,2018,4,9,12,14
18,26 villa Croix-Nivert,5,5,0,0,0,nonexistent,Paris,"Station en parking (niv 0), accÃ¨s 26 villa Cr...",paris-cambronne-parking,...,NaN,0,station,ok,nonexistent,2018,4,9,20,58
19,11 avenue RenÃ© Coty,4,4,0,2,0,operational,Paris,NaN,paris-renecoty-11,...,NaN,0,station,ok,nonexistent,2018,4,9,21,31

The popular hour for picking the Blue-Cars is 22 hrs 58 min

In [12]:
#what is the most popular hour for returning cars?
#
#
df.describe()
df.info()
df.head(20)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 25 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Address              5000 non-null   object
 1   Cars                 5000 non-null   int64
 2   Bluecar counter      5000 non-null   int64
 3   Utilib counter       5000 non-null   int64
 4   Utilib 1.4 counter   5000 non-null   int64
 5   Charge Slots         5000 non-null   int64
 6   Charging Status      5000 non-null   object
 7   City                 5000 non-null   object
 8   Displayed comment    111 non-null    object
 9   ID                   5000 non-null   object
 10  Kind                 5000 non-null   object
 11  Geo point            5000 non-null   object
 12  Postal code          5000 non-null   int64
 13  Public name          5000 non-null   object
 14  Rental status        5000 non-null   object
 15  Scheduled at         47 non-null     object
 16  Slots                5000 non-null   int64
 17  Station type         5000 non-null   object
 18  Status               5000 non-null   object
 19  Subscription status  5000 non-null   object
 20  year                 5000 non-null   int64
 21  month                5000 non-null   int64
 22  day                  5000 non-null   int64
 23  hour                 5000 non-null   int64
 24  minute               5000 non-null   int64
dtypes: int64(12), object(13)
memory usage: 976.7+ KB

,Address,Cars,Bluecar counter,Utilib counter,Utilib 1.4 counter,Charge Slots,Charging Status,City,Displayed comment,ID,...,Scheduled at,Slots,Station type,Status,Subscription status,year,month,day,hour,minute
0,2 Avenue de Suffren,0,0,0,0,0,nonexistent,Paris,NaN,paris-suffren-2,...,NaN,2,station,ok,nonexistent,2018,4,8,11,43
1,145 Rue Raymond Losserand,6,6,0,0,0,operational,Paris,NaN,paris-raymondlosserand-145,...,NaN,0,station,ok,nonexistent,2018,4,6,7,24
2,2 Avenue John Fitzgerald Kennedy,3,3,0,2,0,operational,Le Bourget,NaN,lebourget-johnfitzgeraldkennedy-2,...,NaN,1,station,ok,nonexistent,2018,4,3,20,14
3,51 Rue EugÃ¨ne OudinÃ©,3,3,1,0,1,operational,Paris,NaN,paris-eugeneoudine-51,...,NaN,2,station,ok,nonexistent,2018,4,4,4,37
4,6 avenue de la Porte de Champerret,3,3,0,0,0,nonexistent,Paris,NaN,paris-portedechamperret-6,...,NaN,3,station,ok,nonexistent,2018,4,8,17,23
5,8 Boulevard Voltaire,0,0,0,0,0,nonexistent,Paris,NaN,paris-voltaire-8,...,NaN,4,station,ok,nonexistent,2018,4,6,7,2
6,37 rue Leblanc,0,0,0,0,0,nonexistent,Paris,"Station en parking (niv -1), accÃ¨s 37 rue Leb...",paris-citroencevennes-parking,...,NaN,0,station,closed,nonexistent,2018,4,8,18,20
7,17 Rue des Luaps ProlongÃ©e,3,3,1,0,0,nonexistent,Nanterre,NaN,nanterre-luaps-17,...,NaN,0,station,ok,nonexistent,2018,4,4,22,13
8,34 avenue Jean Moulin,1,1,0,0,0,nonexistent,Paris,NaN,paris-jeanmoulin-34,...,NaN,4,station,ok,nonexistent,2018,4,2,22,58
9,41 boulevard de Rochechouart,6,6,0,0,0,nonexistent,Paris,NaN,paris-anvers-parking,...,NaN,0,station,ok,nonexistent,2018,4,4,15,2
10,14 rue Censier,0,0,0,0,2,operational,Paris,NaN,paris-censier-14,...,NaN,6,station,ok,nonexistent,2018,4,1,4,39
11,12 Rue Francis de PressensÃ©,1,1,0,0,0,nonexistent,Puteaux,NaN,puteaux-francisdepressense-12,...,NaN,4,station,ok,nonexistent,2018,4,6,9,20
12,6 avenue de la Porte de Champerret,5,5,1,0,0,nonexistent,Paris,NaN,paris-portedechamperret-6,...,NaN,0,station,ok,nonexistent,2018,4,5,12,22
13,34 avenue Jean Moulin,0,0,0,0,0,nonexistent,Paris,NaN,paris-jeanmoulin-34,...,NaN,0,station,ok,nonexistent,2018,4,8,21,54
14,8 Boulevard Richard Lenoir,0,0,0,0,1,operational,Paris,NaN,paris-richardlenoir-8,...,NaN,4,station,ok,nonexistent,2018,4,6,8,0
15,3 rue Jean JaurÃ¨s,0,0,0,0,0,nonexistent,Fontenay-aux-Roses,NaN,fontenayauxroses-jeanjaures-3,...,NaN,4,full_station,ok,operational,2018,4,2,0,21
16,2 avenue du GÃ©nÃ©ral Leclerc,0,0,0,0,0,nonexistent,Le Chesnay,NaN,lechesnay-leclerc-2,...,NaN,1,station,ok,nonexistent,2018,4,3,19,0
17,182 Boulevard Voltaire,6,6,0,0,0,operational,Paris,NaN,paris-voltaire-182,...,NaN,0,station,ok,nonexistent,2018,4,9,12,14
18,26 villa Croix-Nivert,5,5,0,0,0,nonexistent,Paris,"Station en parking (niv 0), accÃ¨s 26 villa Cr...",paris-cambronne-parking,...,NaN,0,station,ok,nonexistent,2018,4,9,20,58
19,11 avenue RenÃ© Coty,4,4,0,2,0,operational,Paris,NaN,paris-renecoty-11,...,NaN,0,station,ok,nonexistent,2018,4,9,21,31

The station with most returning cars is fontenayauxroses-jeanjaures-3

In [13]:
#what station is the most popular?
#
df.describe()
df.info()
df.head(20)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 25 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Address              5000 non-null   object
 1   Cars                 5000 non-null   int64
 2   Bluecar counter      5000 non-null   int64
 3   Utilib counter       5000 non-null   int64
 4   Utilib 1.4 counter   5000 non-null   int64
 5   Charge Slots         5000 non-null   int64
 6   Charging Status      5000 non-null   object
 7   City                 5000 non-null   object
 8   Displayed comment    111 non-null    object
 9   ID                   5000 non-null   object
 10  Kind                 5000 non-null   object
 11  Geo point            5000 non-null   object
 12  Postal code          5000 non-null   int64
 13  Public name          5000 non-null   object
 14  Rental status        5000 non-null   object
 15  Scheduled at         47 non-null     object
 16  Slots                5000 non-null   int64
 17  Station type         5000 non-null   object
 18  Status               5000 non-null   object
 19  Subscription status  5000 non-null   object
 20  year                 5000 non-null   int64
 21  month                5000 non-null   int64
 22  day                  5000 non-null   int64
 23  hour                 5000 non-null   int64
 24  minute               5000 non-null   int64
dtypes: int64(12), object(13)
memory usage: 976.7+ KB

,Address,Cars,Bluecar counter,Utilib counter,Utilib 1.4 counter,Charge Slots,Charging Status,City,Displayed comment,ID,...,Scheduled at,Slots,Station type,Status,Subscription status,year,month,day,hour,minute
0,2 Avenue de Suffren,0,0,0,0,0,nonexistent,Paris,NaN,paris-suffren-2,...,NaN,2,station,ok,nonexistent,2018,4,8,11,43
1,145 Rue Raymond Losserand,6,6,0,0,0,operational,Paris,NaN,paris-raymondlosserand-145,...,NaN,0,station,ok,nonexistent,2018,4,6,7,24
2,2 Avenue John Fitzgerald Kennedy,3,3,0,2,0,operational,Le Bourget,NaN,lebourget-johnfitzgeraldkennedy-2,...,NaN,1,station,ok,nonexistent,2018,4,3,20,14
3,51 Rue EugÃ¨ne OudinÃ©,3,3,1,0,1,operational,Paris,NaN,paris-eugeneoudine-51,...,NaN,2,station,ok,nonexistent,2018,4,4,4,37
4,6 avenue de la Porte de Champerret,3,3,0,0,0,nonexistent,Paris,NaN,paris-portedechamperret-6,...,NaN,3,station,ok,nonexistent,2018,4,8,17,23
5,8 Boulevard Voltaire,0,0,0,0,0,nonexistent,Paris,NaN,paris-voltaire-8,...,NaN,4,station,ok,nonexistent,2018,4,6,7,2
6,37 rue Leblanc,0,0,0,0,0,nonexistent,Paris,"Station en parking (niv -1), accÃ¨s 37 rue Leb...",paris-citroencevennes-parking,...,NaN,0,station,closed,nonexistent,2018,4,8,18,20
7,17 Rue des Luaps ProlongÃ©e,3,3,1,0,0,nonexistent,Nanterre,NaN,nanterre-luaps-17,...,NaN,0,station,ok,nonexistent,2018,4,4,22,13
8,34 avenue Jean Moulin,1,1,0,0,0,nonexistent,Paris,NaN,paris-jeanmoulin-34,...,NaN,4,station,ok,nonexistent,2018,4,2,22,58
9,41 boulevard de Rochechouart,6,6,0,0,0,nonexistent,Paris,NaN,paris-anvers-parking,...,NaN,0,station,ok,nonexistent,2018,4,4,15,2
10,14 rue Censier,0,0,0,0,2,operational,Paris,NaN,paris-censier-14,...,NaN,6,station,ok,nonexistent,2018,4,1,4,39
11,12 Rue Francis de PressensÃ©,1,1,0,0,0,nonexistent,Puteaux,NaN,puteaux-francisdepressense-12,...,NaN,4,station,ok,nonexistent,2018,4,6,9,20
12,6 avenue de la Porte de Champerret,5,5,1,0,0,nonexistent,Paris,NaN,paris-portedechamperret-6,...,NaN,0,station,ok,nonexistent,2018,4,5,12,22
13,34 avenue Jean Moulin,0,0,0,0,0,nonexistent,Paris,NaN,paris-jeanmoulin-34,...,NaN,0,station,ok,nonexistent,2018,4,8,21,54
14,8 Boulevard Richard Lenoir,0,0,0,0,1,operational,Paris,NaN,paris-richardlenoir-8,...,NaN,4,station,ok,nonexistent,2018,4,6,8,0
15,3 rue Jean JaurÃ¨s,0,0,0,0,0,nonexistent,Fontenay-aux-Roses,NaN,fontenayauxroses-jeanjaures-3,...,NaN,4,full_station,ok,operational,2018,4,2,0,21
16,2 avenue du GÃ©nÃ©ral Leclerc,0,0,0,0,0,nonexistent,Le Chesnay,NaN,lechesnay-leclerc-2,...,NaN,1,station,ok,nonexistent,2018,4,3,19,0
17,182 Boulevard Voltaire,6,6,0,0,0,operational,Paris,NaN,paris-voltaire-182,...,NaN,0,station,ok,nonexistent,2018,4,9,12,14
18,26 villa Croix-Nivert,5,5,0,0,0,nonexistent,Paris,"Station en parking (niv 0), accÃ¨s 26 villa Cr...",paris-cambronne-parking,...,NaN,0,station,ok,nonexistent,2018,4,9,20,58
19,11 avenue RenÃ© Coty,4,4,0,2,0,operational,Paris,NaN,paris-renecoty-11,...,NaN,0,station,ok,nonexistent,2018,4,9,21,31

The most popular station is Paris jeanmoulin-34

In [14]:
#station at the most popular picking hour?
#
#
df.describe()
df.info()
df.head(20)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 25 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Address              5000 non-null   object
 1   Cars                 5000 non-null   int64
 2   Bluecar counter      5000 non-null   int64
 3   Utilib counter       5000 non-null   int64
 4   Utilib 1.4 counter   5000 non-null   int64
 5   Charge Slots         5000 non-null   int64
 6   Charging Status      5000 non-null   object
 7   City                 5000 non-null   object
 8   Displayed comment    111 non-null    object
 9   ID                   5000 non-null   object
 10  Kind                 5000 non-null   object
 11  Geo point            5000 non-null   object
 12  Postal code          5000 non-null   int64
 13  Public name          5000 non-null   object
 14  Rental status        5000 non-null   object
 15  Scheduled at         47 non-null     object
 16  Slots                5000 non-null   int64
 17  Station type         5000 non-null   object
 18  Status               5000 non-null   object
 19  Subscription status  5000 non-null   object
 20  year                 5000 non-null   int64
 21  month                5000 non-null   int64
 22  day                  5000 non-null   int64
 23  hour                 5000 non-null   int64
 24  minute               5000 non-null   int64
dtypes: int64(12), object(13)
memory usage: 976.7+ KB

,Address,Cars,Bluecar counter,Utilib counter,Utilib 1.4 counter,Charge Slots,Charging Status,City,Displayed comment,ID,...,Scheduled at,Slots,Station type,Status,Subscription status,year,month,day,hour,minute
0,2 Avenue de Suffren,0,0,0,0,0,nonexistent,Paris,NaN,paris-suffren-2,...,NaN,2,station,ok,nonexistent,2018,4,8,11,43
1,145 Rue Raymond Losserand,6,6,0,0,0,operational,Paris,NaN,paris-raymondlosserand-145,...,NaN,0,station,ok,nonexistent,2018,4,6,7,24
2,2 Avenue John Fitzgerald Kennedy,3,3,0,2,0,operational,Le Bourget,NaN,lebourget-johnfitzgeraldkennedy-2,...,NaN,1,station,ok,nonexistent,2018,4,3,20,14
3,51 Rue EugÃ¨ne OudinÃ©,3,3,1,0,1,operational,Paris,NaN,paris-eugeneoudine-51,...,NaN,2,station,ok,nonexistent,2018,4,4,4,37
4,6 avenue de la Porte de Champerret,3,3,0,0,0,nonexistent,Paris,NaN,paris-portedechamperret-6,...,NaN,3,station,ok,nonexistent,2018,4,8,17,23
5,8 Boulevard Voltaire,0,0,0,0,0,nonexistent,Paris,NaN,paris-voltaire-8,...,NaN,4,station,ok,nonexistent,2018,4,6,7,2
6,37 rue Leblanc,0,0,0,0,0,nonexistent,Paris,"Station en parking (niv -1), accÃ¨s 37 rue Leb...",paris-citroencevennes-parking,...,NaN,0,station,closed,nonexistent,2018,4,8,18,20
7,17 Rue des Luaps ProlongÃ©e,3,3,1,0,0,nonexistent,Nanterre,NaN,nanterre-luaps-17,...,NaN,0,station,ok,nonexistent,2018,4,4,22,13
8,34 avenue Jean Moulin,1,1,0,0,0,nonexistent,Paris,NaN,paris-jeanmoulin-34,...,NaN,4,station,ok,nonexistent,2018,4,2,22,58
9,41 boulevard de Rochechouart,6,6,0,0,0,nonexistent,Paris,NaN,paris-anvers-parking,...,NaN,0,station,ok,nonexistent,2018,4,4,15,2
10,14 rue Censier,0,0,0,0,2,operational,Paris,NaN,paris-censier-14,...,NaN,6,station,ok,nonexistent,2018,4,1,4,39
11,12 Rue Francis de PressensÃ©,1,1,0,0,0,nonexistent,Puteaux,NaN,puteaux-francisdepressense-12,...,NaN,4,station,ok,nonexistent,2018,4,6,9,20
12,6 avenue de la Porte de Champerret,5,5,1,0,0,nonexistent,Paris,NaN,paris-portedechamperret-6,...,NaN,0,station,ok,nonexistent,2018,4,5,12,22
13,34 avenue Jean Moulin,0,0,0,0,0,nonexistent,Paris,NaN,paris-jeanmoulin-34,...,NaN,0,station,ok,nonexistent,2018,4,8,21,54
14,8 Boulevard Richard Lenoir,0,0,0,0,1,operational,Paris,NaN,paris-richardlenoir-8,...,NaN,4,station,ok,nonexistent,2018,4,6,8,0
15,3 rue Jean JaurÃ¨s,0,0,0,0,0,nonexistent,Fontenay-aux-Roses,NaN,fontenayauxroses-jeanjaures-3,...,NaN,4,full_station,ok,operational,2018,4,2,0,21
16,2 avenue du GÃ©nÃ©ral Leclerc,0,0,0,0,0,nonexistent,Le Chesnay,NaN,lechesnay-leclerc-2,...,NaN,1,station,ok,nonexistent,2018,4,3,19,0
17,182 Boulevard Voltaire,6,6,0,0,0,operational,Paris,NaN,paris-voltaire-182,...,NaN,0,station,ok,nonexistent,2018,4,9,12,14
18,26 villa Croix-Nivert,5,5,0,0,0,nonexistent,Paris,"Station en parking (niv 0), accÃ¨s 26 villa Cr...",paris-cambronne-parking,...,NaN,0,station,ok,nonexistent,2018,4,9,20,58
19,11 avenue RenÃ© Coty,4,4,0,2,0,operational,Paris,NaN,paris-renecoty-11,...,NaN,0,station,ok,nonexistent,2018,4,9,21,31

Paris-jeanmoulin-34 has the most picking hour

In [ ]:
#what postal code is the most popular for picking the blue_car?
#
df.describe()
df.info()
df.head(20)

In [15]:
#does the most popular station belong to that postal code?
#
#NO
df.describe()
df.info()
df.head(20)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 25 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Address              5000 non-null   object
 1   Cars                 5000 non-null   int64
 2   Bluecar counter      5000 non-null   int64
 3   Utilib counter       5000 non-null   int64
 4   Utilib 1.4 counter   5000 non-null   int64
 5   Charge Slots         5000 non-null   int64
 6   Charging Status      5000 non-null   object
 7   City                 5000 non-null   object
 8   Displayed comment    111 non-null    object
 9   ID                   5000 non-null   object
 10  Kind                 5000 non-null   object
 11  Geo point            5000 non-null   object
 12  Postal code          5000 non-null   int64
 13  Public name          5000 non-null   object
 14  Rental status        5000 non-null   object
 15  Scheduled at         47 non-null     object
 16  Slots                5000 non-null   int64
 17  Station type         5000 non-null   object
 18  Status               5000 non-null   object
 19  Subscription status  5000 non-null   object
 20  year                 5000 non-null   int64
 21  month                5000 non-null   int64
 22  day                  5000 non-null   int64
 23  hour                 5000 non-null   int64
 24  minute               5000 non-null   int64
dtypes: int64(12), object(13)
memory usage: 976.7+ KB

,Address,Cars,Bluecar counter,Utilib counter,Utilib 1.4 counter,Charge Slots,Charging Status,City,Displayed comment,ID,...,Scheduled at,Slots,Station type,Status,Subscription status,year,month,day,hour,minute
0,2 Avenue de Suffren,0,0,0,0,0,nonexistent,Paris,NaN,paris-suffren-2,...,NaN,2,station,ok,nonexistent,2018,4,8,11,43
1,145 Rue Raymond Losserand,6,6,0,0,0,operational,Paris,NaN,paris-raymondlosserand-145,...,NaN,0,station,ok,nonexistent,2018,4,6,7,24
2,2 Avenue John Fitzgerald Kennedy,3,3,0,2,0,operational,Le Bourget,NaN,lebourget-johnfitzgeraldkennedy-2,...,NaN,1,station,ok,nonexistent,2018,4,3,20,14
3,51 Rue EugÃ¨ne OudinÃ©,3,3,1,0,1,operational,Paris,NaN,paris-eugeneoudine-51,...,NaN,2,station,ok,nonexistent,2018,4,4,4,37
4,6 avenue de la Porte de Champerret,3,3,0,0,0,nonexistent,Paris,NaN,paris-portedechamperret-6,...,NaN,3,station,ok,nonexistent,2018,4,8,17,23
5,8 Boulevard Voltaire,0,0,0,0,0,nonexistent,Paris,NaN,paris-voltaire-8,...,NaN,4,station,ok,nonexistent,2018,4,6,7,2
6,37 rue Leblanc,0,0,0,0,0,nonexistent,Paris,"Station en parking (niv -1), accÃ¨s 37 rue Leb...",paris-citroencevennes-parking,...,NaN,0,station,closed,nonexistent,2018,4,8,18,20
7,17 Rue des Luaps ProlongÃ©e,3,3,1,0,0,nonexistent,Nanterre,NaN,nanterre-luaps-17,...,NaN,0,station,ok,nonexistent,2018,4,4,22,13
8,34 avenue Jean Moulin,1,1,0,0,0,nonexistent,Paris,NaN,paris-jeanmoulin-34,...,NaN,4,station,ok,nonexistent,2018,4,2,22,58
9,41 boulevard de Rochechouart,6,6,0,0,0,nonexistent,Paris,NaN,paris-anvers-parking,...,NaN,0,station,ok,nonexistent,2018,4,4,15,2
10,14 rue Censier,0,0,0,0,2,operational,Paris,NaN,paris-censier-14,...,NaN,6,station,ok,nonexistent,2018,4,1,4,39
11,12 Rue Francis de PressensÃ©,1,1,0,0,0,nonexistent,Puteaux,NaN,puteaux-francisdepressense-12,...,NaN,4,station,ok,nonexistent,2018,4,6,9,20
12,6 avenue de la Porte de Champerret,5,5,1,0,0,nonexistent,Paris,NaN,paris-portedechamperret-6,...,NaN,0,station,ok,nonexistent,2018,4,5,12,22
13,34 avenue Jean Moulin,0,0,0,0,0,nonexistent,Paris,NaN,paris-jeanmoulin-34,...,NaN,0,station,ok,nonexistent,2018,4,8,21,54
14,8 Boulevard Richard Lenoir,0,0,0,0,1,operational,Paris,NaN,paris-richardlenoir-8,...,NaN,4,station,ok,nonexistent,2018,4,6,8,0
15,3 rue Jean JaurÃ¨s,0,0,0,0,0,nonexistent,Fontenay-aux-Roses,NaN,fontenayauxroses-jeanjaures-3,...,NaN,4,full_station,ok,operational,2018,4,2,0,21
16,2 avenue du GÃ©nÃ©ral Leclerc,0,0,0,0,0,nonexistent,Le Chesnay,NaN,lechesnay-leclerc-2,...,NaN,1,station,ok,nonexistent,2018,4,3,19,0
17,182 Boulevard Voltaire,6,6,0,0,0,operational,Paris,NaN,paris-voltaire-182,...,NaN,0,station,ok,nonexistent,2018,4,9,12,14
18,26 villa Croix-Nivert,5,5,0,0,0,nonexistent,Paris,"Station en parking (niv 0), accÃ¨s 26 villa Cr...",paris-cambronne-parking,...,NaN,0,station,ok,nonexistent,2018,4,9,20,58
19,11 avenue RenÃ© Coty,4,4,0,2,0,operational,Paris,NaN,paris-renecoty-11,...,NaN,0,station,ok,nonexistent,2018,4,9,21,31

In [16]:
#what postal code is the most popular during picking hour ?
#
df["Postal code"].value_counts()

75015    274
75016    236
75017    221
75011    180
75020    169
        ...
75116      5
93310      4
91400      4
92110      4
94100      2
Name: Postal code, Length: 107, dtype: int64

In [ ]:
#Do the results change if Utilib and Utilib 1.4 instead of Blue_Cars?
#
#